// source: lens_overlay_cluster_info.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var lens_overlay_routing_info_pb = require('./lens_overlay_routing_info_pb.js');
goog.object.extend(proto, lens_overlay_routing_info_pb);
goog.exportSymbol('proto.lens.LensOverlayClusterInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.lens.LensOverlayClusterInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.lens.LensOverlayClusterInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.lens.LensOverlayClusterInfo.displayName = 'proto.lens.LensOverlayClusterInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.lens.LensOverlayClusterInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.lens.LensOverlayClusterInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.lens.LensOverlayClusterInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lens.LensOverlayClusterInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
serverSessionId: jspb.Message.getFieldWithDefault(msg, 1, ""),
searchSessionId: jspb.Message.getFieldWithDefault(msg, 2, ""),
routingInfo: (f = msg.getRoutingInfo()) && lens_overlay_routing_info_pb.LensOverlayRoutingInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.lens.LensOverlayClusterInfo}
 */
proto.lens.LensOverlayClusterInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.lens.LensOverlayClusterInfo;
  return proto.lens.LensOverlayClusterInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.lens.LensOverlayClusterInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.lens.LensOverlayClusterInfo}
 */
proto.lens.LensOverlayClusterInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setServerSessionId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSearchSessionId(value);
      break;
    case 6:
      var value = new lens_overlay_routing_info_pb.LensOverlayRoutingInfo;
      reader.readMessage(value,lens_overlay_routing_info_pb.LensOverlayRoutingInfo.deserializeBinaryFromReader);
      msg.setRoutingInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.lens.LensOverlayClusterInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.lens.LensOverlayClusterInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.lens.LensOverlayClusterInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lens.LensOverlayClusterInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerSessionId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSearchSessionId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRoutingInfo();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      lens_overlay_routing_info_pb.LensOverlayRoutingInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional string server_session_id = 1;
 * @return {string}
 */
proto.lens.LensOverlayClusterInfo.prototype.getServerSessionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.lens.LensOverlayClusterInfo} returns this
 */
proto.lens.LensOverlayClusterInfo.prototype.setServerSessionId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string search_session_id = 2;
 * @return {string}
 */
proto.lens.LensOverlayClusterInfo.prototype.getSearchSessionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.lens.LensOverlayClusterInfo} returns this
 */
proto.lens.LensOverlayClusterInfo.prototype.setSearchSessionId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional LensOverlayRoutingInfo routing_info = 6;
 * @return {?proto.lens.LensOverlayRoutingInfo}
 */
proto.lens.LensOverlayClusterInfo.prototype.getRoutingInfo = function() {
  return /** @type{?proto.lens.LensOverlayRoutingInfo} */ (
    jspb.Message.getWrapperField(this, lens_overlay_routing_info_pb.LensOverlayRoutingInfo, 6));
};


/**
 * @param {?proto.lens.LensOverlayRoutingInfo|undefined} value
 * @return {!proto.lens.LensOverlayClusterInfo} returns this
*/
proto.lens.LensOverlayClusterInfo.prototype.setRoutingInfo = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.lens.LensOverlayClusterInfo} returns this
 */
proto.lens.LensOverlayClusterInfo.prototype.clearRoutingInfo = function() {
  return this.setRoutingInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.lens.LensOverlayClusterInfo.prototype.hasRoutingInfo = function() {
  return jspb.Message.getField(this, 6) != null;
};


goog.object.extend(exports, proto.lens);
