// source: lens_overlay_knowledge_query.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var lens_overlay_knowledge_intent_query_pb = require('./lens_overlay_knowledge_intent_query_pb.js');
goog.object.extend(proto, lens_overlay_knowledge_intent_query_pb);
goog.exportSymbol('proto.lens.Query', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.lens.Query = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, null);
};
goog.inherits(proto.lens.Query, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.lens.Query.displayName = 'proto.lens.Query';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.lens.Query.prototype.toObject = function(opt_includeInstance) {
  return proto.lens.Query.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.lens.Query} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lens.Query.toObject = function(includeInstance, msg) {
  var f, obj = {
intentQuery: (f = msg.getIntentQuery()) && lens_overlay_knowledge_intent_query_pb.FunctionCall.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.lens.Query}
 */
proto.lens.Query.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.lens.Query;
  return proto.lens.Query.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.lens.Query} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.lens.Query}
 */
proto.lens.Query.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 56249026:
      var value = new lens_overlay_knowledge_intent_query_pb.FunctionCall;
      reader.readMessage(value,lens_overlay_knowledge_intent_query_pb.FunctionCall.deserializeBinaryFromReader);
      msg.setIntentQuery(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.lens.Query.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.lens.Query.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.lens.Query} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lens.Query.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIntentQuery();
  if (f != null) {
    writer.writeMessage(
      56249026,
      f,
      lens_overlay_knowledge_intent_query_pb.FunctionCall.serializeBinaryToWriter
    );
  }
};


/**
 * optional FunctionCall intent_query = 56249026;
 * @return {?proto.lens.FunctionCall}
 */
proto.lens.Query.prototype.getIntentQuery = function() {
  return /** @type{?proto.lens.FunctionCall} */ (
    jspb.Message.getWrapperField(this, lens_overlay_knowledge_intent_query_pb.FunctionCall, 56249026));
};


/**
 * @param {?proto.lens.FunctionCall|undefined} value
 * @return {!proto.lens.Query} returns this
*/
proto.lens.Query.prototype.setIntentQuery = function(value) {
  return jspb.Message.setWrapperField(this, 56249026, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.lens.Query} returns this
 */
proto.lens.Query.prototype.clearIntentQuery = function() {
  return this.setIntentQuery(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.lens.Query.prototype.hasIntentQuery = function() {
  return jspb.Message.getField(this, 56249026) != null;
};


goog.object.extend(exports, proto.lens);
