// source: lens_overlay_visual_search_interaction_data.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var lens_overlay_geometry_pb = require('./lens_overlay_geometry_pb.cjs');
goog.object.extend(proto, lens_overlay_geometry_pb);
var lens_overlay_interaction_request_metadata_pb = require('./lens_overlay_interaction_request_metadata_pb.cjs');
goog.object.extend(proto, lens_overlay_interaction_request_metadata_pb);
var lens_overlay_visual_search_interaction_log_data_pb = require('./lens_overlay_visual_search_interaction_log_data_pb.cjs');
goog.object.extend(proto, lens_overlay_visual_search_interaction_log_data_pb);
goog.exportSymbol('proto.lens.LensOverlayVisualSearchInteractionData', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.lens.LensOverlayVisualSearchInteractionData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.lens.LensOverlayVisualSearchInteractionData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.lens.LensOverlayVisualSearchInteractionData.displayName = 'proto.lens.LensOverlayVisualSearchInteractionData';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.lens.LensOverlayVisualSearchInteractionData.prototype.toObject = function(opt_includeInstance) {
  return proto.lens.LensOverlayVisualSearchInteractionData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.lens.LensOverlayVisualSearchInteractionData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lens.LensOverlayVisualSearchInteractionData.toObject = function(includeInstance, msg) {
  var f, obj = {
interactionType: jspb.Message.getFieldWithDefault(msg, 1, 0),
zoomedCrop: (f = msg.getZoomedCrop()) && lens_overlay_geometry_pb.ZoomedCrop.toObject(includeInstance, f),
objectId: jspb.Message.getFieldWithDefault(msg, 3, ""),
logData: (f = msg.getLogData()) && lens_overlay_visual_search_interaction_log_data_pb.LensOverlayVisualSearchInteractionLogData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.lens.LensOverlayVisualSearchInteractionData}
 */
proto.lens.LensOverlayVisualSearchInteractionData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.lens.LensOverlayVisualSearchInteractionData;
  return proto.lens.LensOverlayVisualSearchInteractionData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.lens.LensOverlayVisualSearchInteractionData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.lens.LensOverlayVisualSearchInteractionData}
 */
proto.lens.LensOverlayVisualSearchInteractionData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.lens.LensOverlayInteractionRequestMetadata.Type} */ (reader.readEnum());
      msg.setInteractionType(value);
      break;
    case 7:
      var value = new lens_overlay_geometry_pb.ZoomedCrop;
      reader.readMessage(value,lens_overlay_geometry_pb.ZoomedCrop.deserializeBinaryFromReader);
      msg.setZoomedCrop(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setObjectId(value);
      break;
    case 5:
      var value = new lens_overlay_visual_search_interaction_log_data_pb.LensOverlayVisualSearchInteractionLogData;
      reader.readMessage(value,lens_overlay_visual_search_interaction_log_data_pb.LensOverlayVisualSearchInteractionLogData.deserializeBinaryFromReader);
      msg.setLogData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.lens.LensOverlayVisualSearchInteractionData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.lens.LensOverlayVisualSearchInteractionData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.lens.LensOverlayVisualSearchInteractionData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lens.LensOverlayVisualSearchInteractionData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInteractionType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getZoomedCrop();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      lens_overlay_geometry_pb.ZoomedCrop.serializeBinaryToWriter
    );
  }
  f = message.getObjectId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLogData();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      lens_overlay_visual_search_interaction_log_data_pb.LensOverlayVisualSearchInteractionLogData.serializeBinaryToWriter
    );
  }
};


/**
 * optional LensOverlayInteractionRequestMetadata.Type interaction_type = 1;
 * @return {!proto.lens.LensOverlayInteractionRequestMetadata.Type}
 */
proto.lens.LensOverlayVisualSearchInteractionData.prototype.getInteractionType = function() {
  return /** @type {!proto.lens.LensOverlayInteractionRequestMetadata.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.lens.LensOverlayInteractionRequestMetadata.Type} value
 * @return {!proto.lens.LensOverlayVisualSearchInteractionData} returns this
 */
proto.lens.LensOverlayVisualSearchInteractionData.prototype.setInteractionType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional ZoomedCrop zoomed_crop = 7;
 * @return {?proto.lens.ZoomedCrop}
 */
proto.lens.LensOverlayVisualSearchInteractionData.prototype.getZoomedCrop = function() {
  return /** @type{?proto.lens.ZoomedCrop} */ (
    jspb.Message.getWrapperField(this, lens_overlay_geometry_pb.ZoomedCrop, 7));
};


/**
 * @param {?proto.lens.ZoomedCrop|undefined} value
 * @return {!proto.lens.LensOverlayVisualSearchInteractionData} returns this
*/
proto.lens.LensOverlayVisualSearchInteractionData.prototype.setZoomedCrop = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.lens.LensOverlayVisualSearchInteractionData} returns this
 */
proto.lens.LensOverlayVisualSearchInteractionData.prototype.clearZoomedCrop = function() {
  return this.setZoomedCrop(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.lens.LensOverlayVisualSearchInteractionData.prototype.hasZoomedCrop = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string object_id = 3;
 * @return {string}
 */
proto.lens.LensOverlayVisualSearchInteractionData.prototype.getObjectId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.lens.LensOverlayVisualSearchInteractionData} returns this
 */
proto.lens.LensOverlayVisualSearchInteractionData.prototype.setObjectId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional LensOverlayVisualSearchInteractionLogData log_data = 5;
 * @return {?proto.lens.LensOverlayVisualSearchInteractionLogData}
 */
proto.lens.LensOverlayVisualSearchInteractionData.prototype.getLogData = function() {
  return /** @type{?proto.lens.LensOverlayVisualSearchInteractionLogData} */ (
    jspb.Message.getWrapperField(this, lens_overlay_visual_search_interaction_log_data_pb.LensOverlayVisualSearchInteractionLogData, 5));
};


/**
 * @param {?proto.lens.LensOverlayVisualSearchInteractionLogData|undefined} value
 * @return {!proto.lens.LensOverlayVisualSearchInteractionData} returns this
*/
proto.lens.LensOverlayVisualSearchInteractionData.prototype.setLogData = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.lens.LensOverlayVisualSearchInteractionData} returns this
 */
proto.lens.LensOverlayVisualSearchInteractionData.prototype.clearLogData = function() {
  return this.setLogData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.lens.LensOverlayVisualSearchInteractionData.prototype.hasLogData = function() {
  return jspb.Message.getField(this, 5) != null;
};


goog.object.extend(exports, proto.lens);
