// source: lens_overlay_request_id.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var lens_overlay_routing_info_pb = require('./lens_overlay_routing_info_pb.js');
goog.object.extend(proto, lens_overlay_routing_info_pb);
goog.exportSymbol('proto.lens.LensOverlayRequestId', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.lens.LensOverlayRequestId = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.lens.LensOverlayRequestId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.lens.LensOverlayRequestId.displayName = 'proto.lens.LensOverlayRequestId';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.lens.LensOverlayRequestId.prototype.toObject = function(opt_includeInstance) {
  return proto.lens.LensOverlayRequestId.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.lens.LensOverlayRequestId} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lens.LensOverlayRequestId.toObject = function(includeInstance, msg) {
  var f, obj = {
uuid: jspb.Message.getFieldWithDefault(msg, 1, 0),
sequenceId: jspb.Message.getFieldWithDefault(msg, 2, 0),
imageSequenceId: jspb.Message.getFieldWithDefault(msg, 3, 0),
analyticsId: msg.getAnalyticsId_asB64(),
longContextId: jspb.Message.getFieldWithDefault(msg, 9, 0),
routingInfo: (f = msg.getRoutingInfo()) && lens_overlay_routing_info_pb.LensOverlayRoutingInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.lens.LensOverlayRequestId}
 */
proto.lens.LensOverlayRequestId.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.lens.LensOverlayRequestId;
  return proto.lens.LensOverlayRequestId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.lens.LensOverlayRequestId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.lens.LensOverlayRequestId}
 */
proto.lens.LensOverlayRequestId.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setUuid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSequenceId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setImageSequenceId(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAnalyticsId(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLongContextId(value);
      break;
    case 6:
      var value = new lens_overlay_routing_info_pb.LensOverlayRoutingInfo;
      reader.readMessage(value,lens_overlay_routing_info_pb.LensOverlayRoutingInfo.deserializeBinaryFromReader);
      msg.setRoutingInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.lens.LensOverlayRequestId.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.lens.LensOverlayRequestId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.lens.LensOverlayRequestId} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lens.LensOverlayRequestId.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUuid();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getSequenceId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getImageSequenceId();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getAnalyticsId_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getLongContextId();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getRoutingInfo();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      lens_overlay_routing_info_pb.LensOverlayRoutingInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint64 uuid = 1;
 * @return {number}
 */
proto.lens.LensOverlayRequestId.prototype.getUuid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.lens.LensOverlayRequestId} returns this
 */
proto.lens.LensOverlayRequestId.prototype.setUuid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 sequence_id = 2;
 * @return {number}
 */
proto.lens.LensOverlayRequestId.prototype.getSequenceId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.lens.LensOverlayRequestId} returns this
 */
proto.lens.LensOverlayRequestId.prototype.setSequenceId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 image_sequence_id = 3;
 * @return {number}
 */
proto.lens.LensOverlayRequestId.prototype.getImageSequenceId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.lens.LensOverlayRequestId} returns this
 */
proto.lens.LensOverlayRequestId.prototype.setImageSequenceId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional bytes analytics_id = 4;
 * @return {!(string|Uint8Array)}
 */
proto.lens.LensOverlayRequestId.prototype.getAnalyticsId = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes analytics_id = 4;
 * This is a type-conversion wrapper around `getAnalyticsId()`
 * @return {string}
 */
proto.lens.LensOverlayRequestId.prototype.getAnalyticsId_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAnalyticsId()));
};


/**
 * optional bytes analytics_id = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAnalyticsId()`
 * @return {!Uint8Array}
 */
proto.lens.LensOverlayRequestId.prototype.getAnalyticsId_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAnalyticsId()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.lens.LensOverlayRequestId} returns this
 */
proto.lens.LensOverlayRequestId.prototype.setAnalyticsId = function(value) {
  return jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional int32 long_context_id = 9;
 * @return {number}
 */
proto.lens.LensOverlayRequestId.prototype.getLongContextId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.lens.LensOverlayRequestId} returns this
 */
proto.lens.LensOverlayRequestId.prototype.setLongContextId = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional LensOverlayRoutingInfo routing_info = 6;
 * @return {?proto.lens.LensOverlayRoutingInfo}
 */
proto.lens.LensOverlayRequestId.prototype.getRoutingInfo = function() {
  return /** @type{?proto.lens.LensOverlayRoutingInfo} */ (
    jspb.Message.getWrapperField(this, lens_overlay_routing_info_pb.LensOverlayRoutingInfo, 6));
};


/**
 * @param {?proto.lens.LensOverlayRoutingInfo|undefined} value
 * @return {!proto.lens.LensOverlayRequestId} returns this
*/
proto.lens.LensOverlayRequestId.prototype.setRoutingInfo = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.lens.LensOverlayRequestId} returns this
 */
proto.lens.LensOverlayRequestId.prototype.clearRoutingInfo = function() {
  return this.setRoutingInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.lens.LensOverlayRequestId.prototype.hasRoutingInfo = function() {
  return jspb.Message.getField(this, 6) != null;
};


goog.object.extend(exports, proto.lens);
