// source: lens_overlay_image_crop.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var lens_overlay_geometry_pb = require('./lens_overlay_geometry_pb.js');
goog.object.extend(proto, lens_overlay_geometry_pb);
var lens_overlay_payload_pb = require('./lens_overlay_payload_pb.js');
goog.object.extend(proto, lens_overlay_payload_pb);
goog.exportSymbol('proto.lens.ImageCrop', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.lens.ImageCrop = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.lens.ImageCrop, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.lens.ImageCrop.displayName = 'proto.lens.ImageCrop';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.lens.ImageCrop.prototype.toObject = function(opt_includeInstance) {
  return proto.lens.ImageCrop.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.lens.ImageCrop} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lens.ImageCrop.toObject = function(includeInstance, msg) {
  var f, obj = {
cropId: jspb.Message.getFieldWithDefault(msg, 1, ""),
image: (f = msg.getImage()) && lens_overlay_payload_pb.ClientImage.toObject(includeInstance, f),
zoomedCrop: (f = msg.getZoomedCrop()) && lens_overlay_geometry_pb.ZoomedCrop.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.lens.ImageCrop}
 */
proto.lens.ImageCrop.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.lens.ImageCrop;
  return proto.lens.ImageCrop.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.lens.ImageCrop} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.lens.ImageCrop}
 */
proto.lens.ImageCrop.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCropId(value);
      break;
    case 2:
      var value = new lens_overlay_payload_pb.ClientImage;
      reader.readMessage(value,lens_overlay_payload_pb.ClientImage.deserializeBinaryFromReader);
      msg.setImage(value);
      break;
    case 3:
      var value = new lens_overlay_geometry_pb.ZoomedCrop;
      reader.readMessage(value,lens_overlay_geometry_pb.ZoomedCrop.deserializeBinaryFromReader);
      msg.setZoomedCrop(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.lens.ImageCrop.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.lens.ImageCrop.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.lens.ImageCrop} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lens.ImageCrop.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCropId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getImage();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      lens_overlay_payload_pb.ClientImage.serializeBinaryToWriter
    );
  }
  f = message.getZoomedCrop();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      lens_overlay_geometry_pb.ZoomedCrop.serializeBinaryToWriter
    );
  }
};


/**
 * optional string crop_id = 1;
 * @return {string}
 */
proto.lens.ImageCrop.prototype.getCropId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.lens.ImageCrop} returns this
 */
proto.lens.ImageCrop.prototype.setCropId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ClientImage image = 2;
 * @return {?proto.lens.ClientImage}
 */
proto.lens.ImageCrop.prototype.getImage = function() {
  return /** @type{?proto.lens.ClientImage} */ (
    jspb.Message.getWrapperField(this, lens_overlay_payload_pb.ClientImage, 2));
};


/**
 * @param {?proto.lens.ClientImage|undefined} value
 * @return {!proto.lens.ImageCrop} returns this
*/
proto.lens.ImageCrop.prototype.setImage = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.lens.ImageCrop} returns this
 */
proto.lens.ImageCrop.prototype.clearImage = function() {
  return this.setImage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.lens.ImageCrop.prototype.hasImage = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ZoomedCrop zoomed_crop = 3;
 * @return {?proto.lens.ZoomedCrop}
 */
proto.lens.ImageCrop.prototype.getZoomedCrop = function() {
  return /** @type{?proto.lens.ZoomedCrop} */ (
    jspb.Message.getWrapperField(this, lens_overlay_geometry_pb.ZoomedCrop, 3));
};


/**
 * @param {?proto.lens.ZoomedCrop|undefined} value
 * @return {!proto.lens.ImageCrop} returns this
*/
proto.lens.ImageCrop.prototype.setZoomedCrop = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.lens.ImageCrop} returns this
 */
proto.lens.ImageCrop.prototype.clearZoomedCrop = function() {
  return this.setZoomedCrop(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.lens.ImageCrop.prototype.hasZoomedCrop = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.lens);
